name: CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install
        run: pnpm -w install --frozen-lockfile

      - name: Pre-commit
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all-files

      - name: Lint
        run: pnpm -w lint

      - name: Test
        run: pnpm -w test

      - name: Build web
        run: pnpm -C apps/web build

  build-macos:
    runs-on: macos-latest
    steps:
      - run: 'echo "TODO: implement macOS CI pipeline"'

  build-windows:
    runs-on: windows-latest
    steps:
      - run: 'echo "TODO: implement Windows CI pipeline"'
