name: CI
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Install
        run: pnpm -w install --frozen-lockfile

      - name: Lint
        run: pnpm -w lint || true

      - name: Test
        run: pnpm -w test

      - name: Build web
        run: pnpm -C apps/web build
